apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-11-29T01:30:55Z
  generation: 1
  labels:
    run: prometheus-demo
  name: prometheus-demo
  namespace: default
  resourceVersion: "1220091"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/prometheus-demo
  uid: 6adb9339-f376-11e8-8bdb-42010a8a0039
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: prometheus-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"      # must be quoted
        prometheus.io/port: "8080" # must be quoted
        prometheus.io/path: "/stats"      # it defaults to /metrics, but this is what you said in your first email
      creationTimestamp: null
      labels:
        run: prometheus-demo
    spec:
      containers:
      - image: gcr.io/yuri-next2019/prometheus-demo:latest
        imagePullPolicy: Always
        name: prometheus-demo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-11-29T01:30:55Z
    lastUpdateTime: 2018-11-29T01:31:36Z
    message: ReplicaSet "prometheus-demo-67c97d76c6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-11-29T17:41:53Z
    lastUpdateTime: 2018-11-29T17:41:53Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
